[SPC-level]
partof = 'REQ-tk_app'
text = '''
The actual game where clues are displayed to the user and they have to 
guess what the answer text is.
'''

[SPC-level-solution_input]
text = '''
A text input and a submit button that allow the user to check a solution.

## Processing input

remove chars matching [^A-Za-z0-9] then lowercase prior to submission

~20 max chars
'''

[TST-level-solution_input]
text = '''
Assert that the solution input box is displayed
'''

[TST-level-solution_input-additional_clues]
partof =  'SPC-level-clue'
text = '''
Assert that additional clues are displayed when a partially correct solution
is entered.
'''

[TST-level-solution_input-wrong_submission]
text = '''
Assert that a wrong solution message is displayed
'''

[TST-level-solution_input-correct_submission]
text = '''
Assert that the user progresses to the next level when they enter a correct solution
'''

[TST-level]
text = '''
Assert a logged in user can navigate to the level page though the level list.
'''

[SPC-level-guesses]
text = '''
Display previous guesses for the level.
'''