cache:
  directories:
    - "node_modules"
language: node_js 
node_js:
  - "8"

services:
  - docker

install:
  - npm install
  - npm install -g firebase-tools

script:
  - npm test
  - npm run e2e-travis 
  - if [ "$TRAVIS_BRANCH" == "stable" ]; then npm run deploy-dev; fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then npm run deploy-prod; fi