[SPC-account]
partof = 'REQ-tk_app'
text = '''
Displays user account info and provides account
related functionality.
'''

[TST-account]
text = '''
Assert logged in user can navigate to the account page.
'''

[SPC-account-title]
text = '''
Username is displayed on the top of the page.
'''

[TST-account-title]
text = '''
Verify that the correct username is displayed for various account types.
'''

[SPC-account-delete]
text = '''
Deletes the account remove all data related to it from the site.

When confirming deletion, a warning is displayed
about the user being removed from the hall of fame.
'''

[TST-account-delete]
text = '''
Expect delete confirmation message to be present.
'''

[SPC-account-change_password]
text = '''
For email authentication, a change password form allows password to be modified.
'''

[TST-account-change_password]
text = '''
Test changing password
'''