[SPC-hof-form]
text = '''
When the user finishs all puzzles this screen will appear with a "Congratulations" message,
a donate button, and a HOF comment submission field
'''

[TST-hof-form]

[SPC-hof-form-comment]
text = '''
A required comment field that stores the user's comment for the hall of fame.
'''

[TST-hof-form-comment]