[SPC-nav_bar]
partof = 'REQ-tk_app'
text = '''
The nav bar is always present at the top of the page and provides
navigation to various pages depending on the login state of
the user.

### Links:

Always Displayed
* Getting Started
* Hall of Fame

Logged out
* Sign in

Logged in
* Account Settings
* Levels
* Play - goes to current level
'''

[TST-nav_bar]
text = '''
Verify that the nav bar displays the correct links when logged in and logged out.
'''